Este notebook foi criado para importar a tabela de Resíduos Sólidos em Excel para o ambiente do Google Colab. Aqui mostraremos a importação da tabela, assim como a criação das tabelas.

In [1]:
# Importação das bibliotecas que utilizaremos
import pandas as pd
import math

In [2]:
# Importação do arquivo de tabela a ser utilizado, através do path na seção "Files" do Colab, contendo as informações de resíduos sólidos
file='./Solid_waste_pt.xlsx'

In [3]:
# Visão geral da tabela
df=pd.read_excel(file)
df

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg
0,Zona Norte,Reciclável,Comercial,Compostagem,542.4,50.7,11.5,10.6,167.0,98.0,19.2
1,Zona Oeste,Orgânico,Residencial,Compostagem,223.1,321.1,81.6,8.6,140.2,0.0,8.1
2,Zona Leste,Orgânico,Residencial,Aterro Sanitário,356.3,341.2,77.6,18.0,184.2,10.1,3.6
3,Zona Leste,Orgânico,Residencial,Aterro Sanitário,275.9,371.8,77.0,17.2,178.8,5.2,6.5
4,Centro,Orgânico,Industrial,Reciclagem,942.3,367.1,76.6,11.7,126.8,7.0,4.2
...,...,...,...,...,...,...,...,...,...,...,...
289,Zona Oeste,Orgânico,Comercial,Aterro Sanitário,680.6,355.4,57.1,7.9,137.9,1.3,1.0
290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,Varíaveis qualitativas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
293,Varíaveis quantitativas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Tabela que mostra a quantidade de coletas realizadas em cada regiao
df_Origem_Residuo=df.Origem_Residuo.value_counts()
df_Origem_Residuo

Origem_Residuo
Residencial          143
Comercial             67
Industrial            58
Serviços de Saúde     22
Name: count, dtype: int64

In [6]:
# Ordenação da tabela em ordem alfabética
df_Origem_Residuo=df.Origem_Residuo.value_counts().sort_index()
df_Origem_Residuo

Origem_Residuo
Comercial             67
Industrial            58
Residencial          143
Serviços de Saúde     22
Name: count, dtype: int64

In [7]:
# Impressão do total das coletas realizadas
total_df_Origem_Residuo=df_Origem_Residuo.sum()
total_df_Origem_Residuo

np.int64(290)

In [8]:
# Impressão da tabela com as Regiões de Coleta ordenadas de forma alfabética
dados_v_Origem_Residuo=pd.DataFrame(df_Origem_Residuo)
dados_v_Origem_Residuo

                   count
Origem_Residuo
Comercial             67
Industrial            58
Residencial          143
Serviços de Saúde     22

In [10]:
# Reinicia os índices da região de coleta
dados_v_Origem_Residuo=pd.DataFrame(df_Origem_Residuo).reset_index()
# Renomeia as colunas na tabela com o total de resíduos coletados em cada região da cidade
dados_v_Origem_Residuo.columns=['Origem de Coleta','Total']
dados_v_Origem_Residuo

print(dados_v_Origem_Residuo)

    Origem de Coleta  Total
0          Comercial     67
1         Industrial     58
2        Residencial    143
3  Serviços de Saúde     22

In [11]:
# Cálculo da frequência relativa
dados_v_Origem_Residuo['Frequência relativa(%)']=round((dados_v_Origem_Residuo['Total']/total_df_Origem_Residuo)*100,2)
print(dados_v_Origem_Residuo)

    Origem de Coleta  Total  Frequência relativa(%)
0          Comercial     67                   23.10
1         Industrial     58                   20.00
2        Residencial    143                   49.31
3  Serviços de Saúde     22                    7.59

In [13]:
# Criação de uma tabela com os dados de total de resíduos sólidos de cada região e a frequência relativa de porcentagem de cada região
tabela_Dados_v_Origem_Residuo=pd.DataFrame(dados_v_Origem_Residuo)
tabela_Dados_v_Origem_Residuo

    Origem de Coleta  Total  Frequência relativa(%)
0          Comercial     67                   23.10
1         Industrial     58                   20.00
2        Residencial    143                   49.31
3  Serviços de Saúde     22                    7.59

In [ ]:
df_Tipo_Residuo=df.Tipo_Residuo.value_counts().sort_index()
df_Tipo_Residuo

Tipo_Residuo
Orgânico      119
Perigoso       19
Reciclável     93
Rejeito        59
Name: count, dtype: int64

In [ ]:
df_Tipo_Residuo_Data_set=pd.DataFrame(df_Tipo_Residuo).reset_index()
df_Tipo_Residuo_Data_set.columns=['Tipo de Residuo','Total']
df_Tipo_Residuo_Data_set["Frequencia relativa(%)"]=round((df_Tipo_Residuo_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Tipo_Residuo_Data_set)

  Tipo de Residuo  Total  Frequencia relativa(%)
0        Orgânico    119                  41.034
1        Perigoso     19                   6.552
2      Reciclável     93                  32.069
3         Rejeito     59                  20.345

In [ ]:
tabela_Tipo_Residuo=pd.DataFrame(df_Tipo_Residuo_Data_set)
tabela_Tipo_Residuo

  Tipo de Residuo  Total  Frequencia relativa(%)
0        Orgânico    119                  41.034
1        Perigoso     19                   6.552
2      Reciclável     93                  32.069
3         Rejeito     59                  20.345

In [ ]:
df_Origem_Residuo=df.Origem_Residuo.value_counts().sort_index()
df_Origem_Residuo

Origem_Residuo
Comercial             67
Industrial            58
Residencial          143
Serviços de Saúde     22
Name: count, dtype: int64

In [ ]:
df_Origem_Residuo_Data_set=pd.DataFrame(df_Origem_Residuo).reset_index()
df_Origem_Residuo_Data_set.columns=['Origem de Residuo','Total']
df_Origem_Residuo_Data_set["Frequencia relativa(%)"]=round((df_Origem_Residuo_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Origem_Residuo_Data_set)

   Origem de Residuo  Total  Frequencia relativa(%)
0          Comercial     67                  23.103
1         Industrial     58                  20.000
2        Residencial    143                  49.310
3  Serviços de Saúde     22                   7.586

In [ ]:
tabela_Origem_Residuo=pd.DataFrame(df_Origem_Residuo_Data_set)
tabela_Origem_Residuo

   Origem de Residuo  Total  Frequencia relativa(%)
0          Comercial     67                  23.103
1         Industrial     58                  20.000
2        Residencial    143                  49.310
3  Serviços de Saúde     22                   7.586