Este notebook foi criado para importar a tabela de Resíduos Sólidos em Excel para o ambiente do Google Colab. Aqui mostraremos a importação da tabela, assim como a criação das tabelas.

In [170]:
# Importação das bibliotecas que utilizaremos
import pandas as pd
import math

In [171]:
# Importação do arquivo de tabela a ser utilizado, através do path na seção "Files" do Colab, contendo as informações de resíduos sólidos
file='./Solid_waste_pt.xlsx'

In [172]:
# Visão geral da tabela
df=pd.read_excel(file)
df

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg
0,Zona Norte,Reciclável,Comercial,Compostagem,542.4,50.7,11.5,10.6,167.0,98.0,19.2
1,Zona Leste,Reciclável,Industrial,Aterro Sanitário,1890.8,75.2,13.7,5.1,76.4,81.9,18.2
2,Zona Sul,Reciclável,Residencial,Compostagem,286.1,82.4,5.3,20.0,174.1,98.0,17.4
3,Zona Norte,Orgânico,Residencial,Incineração,464.5,245.4,76.5,22.5,154.1,0.0,5.8
4,Zona Oeste,Reciclável,Residencial,Compostagem,195.6,75.8,14.1,7.8,133.7,95.5,20.2
...,...,...,...,...,...,...,...,...,...,...,...
285,Zona Sul,Reciclável,Residencial,Incineração,377.1,40.0,6.2,17.4,170.3,87.8,19.6
286,Zona Oeste,Orgânico,Serviços de Saúde,Aterro Sanitário,61.6,351.9,57.8,5.4,133.9,6.4,6.4
287,Zona Leste,Reciclável,Industrial,Incineração,1551.8,57.0,2.0,4.3,118.9,87.6,19.8
288,Zona Oeste,Orgânico,Serviços de Saúde,Compostagem,78.8,372.2,52.2,12.0,175.5,0.0,2.8
289,Zona Leste,Orgânico,Serviços de Saúde,Aterro Sanitário,58.7,346.8,72.5,16.3,163.5,2.5,8.3

In [173]:
# Tabela que mostra a quantidade de coletas realizadas em cada regiao
df_Regiao_Coleta=df.Regiao_Coleta.value_counts()
df_Regiao_Coleta

Regiao_Coleta
Zona Norte    70
Zona Leste    67
Zona Sul      55
Zona Oeste    51
Centro        47
Name: count, dtype: int64

In [174]:
# Ordenação da tabela em ordem alfabética
df_Regiao_Coleta=df.Regiao_Coleta.value_counts().sort_index()
df_Regiao_Coleta

Regiao_Coleta
Centro        47
Zona Leste    67
Zona Norte    70
Zona Oeste    51
Zona Sul      55
Name: count, dtype: int64

In [175]:
# Impressão do total das coletas realizadas
total_df_Regiao_Coleta=df_Regiao_Coleta.sum()
total_df_Regiao_Coleta

np.int64(290)

In [176]:
# Impressão da tabela com as Regiões de Coleta ordenadas de forma alfabética
dados_v_Regiao_Coleta=pd.DataFrame(df_Regiao_Coleta)
dados_v_Regiao_Coleta

               count
Regiao_Coleta
Centro            47
Zona Leste        67
Zona Norte        70
Zona Oeste        51
Zona Sul          55

In [177]:
# Reinicia os índices da região de coleta
dados_v_Regiao_Coleta=pd.DataFrame(df_Regiao_Coleta).reset_index()
# Renomeia as colunas na tabela com o total de resíduos coletados em cada região da cidade
dados_v_Regiao_Coleta.columns=['Região de Coleta','Total']
dados_v_Regiao_Coleta

print(dados_v_Regiao_Coleta)

  Região de Coleta  Total
0           Centro     47
1       Zona Leste     67
2       Zona Norte     70
3       Zona Oeste     51
4         Zona Sul     55

In [178]:
# Cálculo da frequência relativa
dados_v_Regiao_Coleta['Frequência relativa(%)']=round((dados_v_Regiao_Coleta['Total']/total_df_Regiao_Coleta)*100,2)
print(dados_v_Regiao_Coleta)

  Região de Coleta  Total  Frequência relativa(%)
0           Centro     47                   16.21
1       Zona Leste     67                   23.10
2       Zona Norte     70                   24.14
3       Zona Oeste     51                   17.59
4         Zona Sul     55                   18.97

In [179]:
# Criação de uma tabela com os dados de total de resíduos sólidos de cada região e a frequência relativa de porcentagem de cada região
tabela_Dados_v_Regiao_Coleta=pd.DataFrame(dados_v_Regiao_Coleta)
tabela_Dados_v_Regiao_Coleta

  Região de Coleta  Total  Frequência relativa(%)
0           Centro     47                   16.21
1       Zona Leste     67                   23.10
2       Zona Norte     70                   24.14
3       Zona Oeste     51                   17.59
4         Zona Sul     55                   18.97

In [180]:
df_Tipo_Residuo=df.Tipo_Residuo.value_counts().sort_index()
df_Tipo_Residuo

Tipo_Residuo
Orgânico      119
Perigoso       19
Reciclável     93
Rejeito        59
Name: count, dtype: int64

In [181]:
df_Tipo_Residuo_Data_set=pd.DataFrame(df_Tipo_Residuo).reset_index()
df_Tipo_Residuo_Data_set.columns=['Tipo de Residuo','Total']
df_Tipo_Residuo_Data_set["Frequencia relativa(%)"]=round((df_Tipo_Residuo_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Tipo_Residuo_Data_set)

  Tipo de Residuo  Total  Frequencia relativa(%)
0        Orgânico    119                  41.034
1        Perigoso     19                   6.552
2      Reciclável     93                  32.069
3         Rejeito     59                  20.345

In [182]:
tabela_Tipo_Residuo=pd.DataFrame(df_Tipo_Residuo_Data_set)
tabela_Tipo_Residuo

  Tipo de Residuo  Total  Frequencia relativa(%)
0        Orgânico    119                  41.034
1        Perigoso     19                   6.552
2      Reciclável     93                  32.069
3         Rejeito     59                  20.345

In [183]:
df_Origem_Residuo=df.Origem_Residuo.value_counts().sort_index()
df_Origem_Residuo

Origem_Residuo
Comercial             67
Industrial            58
Residencial          143
Serviços de Saúde     22
Name: count, dtype: int64

In [184]:
df_Origem_Residuo_Data_set=pd.DataFrame(df_Origem_Residuo).reset_index()
df_Origem_Residuo_Data_set.columns=['Origem de Residuo','Total']
df_Origem_Residuo_Data_set["Frequencia relativa(%)"]=round((df_Origem_Residuo_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Origem_Residuo_Data_set)

   Origem de Residuo  Total  Frequencia relativa(%)
0          Comercial     67                  23.103
1         Industrial     58                  20.000
2        Residencial    143                  49.310
3  Serviços de Saúde     22                   7.586

In [185]:
tabela_Origem_Residuo=pd.DataFrame(df_Origem_Residuo_Data_set)
tabela_Origem_Residuo

   Origem de Residuo  Total  Frequencia relativa(%)
0          Comercial     67                  23.103
1         Industrial     58                  20.000
2        Residencial    143                  49.310
3  Serviços de Saúde     22                   7.586

In [186]:
df_Metodo_Destinacao=df.Metodo_Destinacao.value_counts().sort_index()
df_Metodo_Destinacao

Metodo_Destinacao
Aterro Sanitário    124
Compostagem          55
Incineração          26
Reciclagem           85
Name: count, dtype: int64

In [187]:
df_Metodo_Destinacao_Data_set=pd.DataFrame(df_Metodo_Destinacao).reset_index()
df_Metodo_Destinacao_Data_set.columns=['Método de Destinação', 'Total']
df_Metodo_Destinacao_Data_set["Frequencia relativa(%)"]=round((df_Metodo_Destinacao_Data_set["Total"]/total_df_Regiao_Coleta)*100,3)
print(df_Metodo_Destinacao_Data_set)

  Método de Destinação  Total  Frequencia relativa(%)
0     Aterro Sanitário    124                  42.759
1          Compostagem     55                  18.966
2          Incineração     26                   8.966
3           Reciclagem     85                  29.310

In [188]:
tabela_Metodo_Destinacao=pd.DataFrame(df_Metodo_Destinacao_Data_set)
tabela_Metodo_Destinacao

  Método de Destinação  Total  Frequencia relativa(%)
0     Aterro Sanitário    124                  42.759
1          Compostagem     55                  18.966
2          Incineração     26                   8.966
3           Reciclagem     85                  29.310