Este notebook foi criado para importar a tabela de Resíduos Sólidos em Excel para o ambiente do Google Colab. Aqui mostraremos a importação da tabela, assim como a criação das tabelas.

In [4]:
# Importação das bibliotecas que utilizaremos
import pandas as pd
import math

In [5]:
# Importação do arquivo de tabela a ser utilizado, através do path na seção "Files" do Colab, contendo as informações de resíduos sólidos
file='./Solid_waste_pt.xlsx'

In [6]:
# Visão geral da tabela
df=pd.read_excel(file)
df

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg
0,Zona Oeste,Reciclável,Residencial,Compostagem,195.6,75.8,14.1,7.8,133.7,95.5,20.2
1,Zona Norte,Reciclável,Industrial,Compostagem,1643.5,50.5,2.0,14.1,204.2,87.5,17.2
2,Zona Leste,Reciclável,Comercial,Aterro Sanitário,921.1,95.4,15.8,6.3,134.7,82.5,16.6
3,Centro,Perigoso,Industrial,Reciclagem,1729.7,263.1,16.8,6.2,348.7,0.7,21.4
4,Zona Leste,Reciclável,Industrial,Incineração,1551.8,57.0,2.0,4.3,118.9,87.6,19.8
...,...,...,...,...,...,...,...,...,...,...,...
285,Centro,Orgânico,Industrial,Aterro Sanitário,1754.6,301.5,60.6,10.4,137.6,12.2,8.5
286,Zona Norte,Reciclável,Industrial,Compostagem,913.3,122.2,3.2,4.9,119.0,84.2,18.2
287,Zona Oeste,Rejeito,Comercial,Aterro Sanitário,616.1,159.2,32.3,33.7,259.7,5.2,14.8
288,Zona Sul,Orgânico,Residencial,Reciclagem,232.3,340.7,66.6,16.2,169.1,15.1,7.0
289,Zona Sul,Rejeito,Comercial,Aterro Sanitário,761.9,218.7,27.1,21.3,152.6,8.4,8.9

In [7]:
# Tabela que mostra a quantidade de coletas realizadas em cada regiao
df_Poder_Calorifico_MJkg=df.Poder_Calorifico_MJkg.value_counts()
df_Poder_Calorifico_MJkg

Poder_Calorifico_MJkg
19.2    5
8.8     5
7.6     4
9.3     4
20.8    4
       ..
11.0    1
8.3     1
25.5    1
8.5     1
7.0     1
Name: count, Length: 166, dtype: int64

In [8]:
# Ordenação da tabela em ordem alfabética
df_Poder_Calorifico_MJkg=df.Poder_Calorifico_MJkg.value_counts().sort_index()
df_Poder_Calorifico_MJkg

Poder_Calorifico_MJkg
1.0     3
1.2     1
1.3     1
1.7     1
1.8     1
       ..
24.0    1
24.1    1
25.5    1
25.9    1
26.3    1
Name: count, Length: 166, dtype: int64

In [9]:
# Impressão do total das coletas realizadas
total_df_Poder_Calorifico_MJkg=df_Poder_Calorifico_MJkg.sum()
total_df_Poder_Calorifico_MJkg

np.int64(290)

In [10]:
# Impressão da tabela com as Regiões de Coleta ordenadas de forma alfabética
dados_v_Poder_Calorifico_MJkg=pd.DataFrame(df_Poder_Calorifico_MJkg)
dados_v_Poder_Calorifico_MJkg

                       count
Poder_Calorifico_MJkg
1.0                        3
1.2                        1
1.3                        1
1.7                        1
1.8                        1
...                      ...
24.0                       1
24.1                       1
25.5                       1
25.9                       1
26.3                       1

[166 rows x 1 columns]

In [11]:
# @title
# Reinicia os índices da região de coleta
dados_v_Poder_Calorifico_MJkg=pd.DataFrame(df_Poder_Calorifico_MJkg).reset_index()
# Renomeia as colunas na tabela com o total de resíduos coletados em cada região da cidade
dados_v_Poder_Calorifico_MJkg.columns=['Poder Calorífico','Total']
dados_v_Poder_Calorifico_MJkg

print(dados_v_Poder_Calorifico_MJkg)

     Poder Calorífico  Total
0                 1.0      3
1                 1.2      1
2                 1.3      1
3                 1.7      1
4                 1.8      1
..                ...    ...
161              24.0      1
162              24.1      1
163              25.5      1
164              25.9      1
165              26.3      1

[166 rows x 2 columns]

In [12]:
# Cálculo da frequência relativa
dados_v_Poder_Calorifico_MJkg['Frequência relativa(%)']=round((dados_v_Poder_Calorifico_MJkg['Total']/total_df_Poder_Calorifico_MJkg)*100,2)
print(dados_v_Poder_Calorifico_MJkg)

     Poder Calorífico  Total  Frequência relativa(%)
0                 1.0      3                    1.03
1                 1.2      1                    0.34
2                 1.3      1                    0.34
3                 1.7      1                    0.34
4                 1.8      1                    0.34
..                ...    ...                     ...
161              24.0      1                    0.34
162              24.1      1                    0.34
163              25.5      1                    0.34
164              25.9      1                    0.34
165              26.3      1                    0.34

[166 rows x 3 columns]

In [13]:
tabela_Poder_Calorifico_MJkg=pd.DataFrame(dados_v_Poder_Calorifico_MJkg)
tabela_Poder_Calorifico_MJkg

     Poder Calorífico  Total  Frequência relativa(%)
0                 1.0      3                    1.03
1                 1.2      1                    0.34
2                 1.3      1                    0.34
3                 1.7      1                    0.34
4                 1.8      1                    0.34
..                ...    ...                     ...
161              24.0      1                    0.34
162              24.1      1                    0.34
163              25.5      1                    0.34
164              25.9      1                    0.34
165              26.3      1                    0.34

[166 rows x 3 columns]