In [11]:
import pandas as pd

In [12]:
arquivo='Solid_waste_pt_categorizado.xlsx'

In [13]:
df=pd.read_excel(arquivo)

In [14]:
df

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg,Apropriado_Para_Biodigestor?,Origem_Residuo_Classificado
0,Centro,Reciclável,Residencial,Reciclagem,345.0,112.3,2.0,15.3,167.7,83.3,21.2,Inapropriado,Residencial
1,Centro,Reciclável,Industrial,Aterro Sanitário,1007.2,50.7,2.0,6.1,124.7,79.4,20.1,Inapropriado,Outros
2,Zona Leste,Reciclável,Industrial,Incineração,1551.8,57.0,2.0,4.3,118.9,87.6,19.8,Inapropriado,Outros
3,Zona Norte,Reciclável,Serviços de Saúde,Aterro Sanitário,89.6,57.3,2.0,3.5,124.1,94.6,19.8,Inapropriado,Outros
4,Zona Leste,Reciclável,Serviços de Saúde,Reciclagem,48.7,162.2,2.0,12.2,129.8,91.8,19.5,Inapropriado,Outros
...,...,...,...,...,...,...,...,...,...,...,...,...,...
285,Zona Leste,Orgânico,Residencial,Aterro Sanitário,275.9,371.8,77.0,17.2,178.8,5.2,6.5,Apropriado,Residencial
286,Zona Norte,Orgânico,Comercial,Aterro Sanitário,471.8,338.4,77.2,52.9,262.3,5.0,8.1,Apropriado,Outros
287,Zona Leste,Orgânico,Residencial,Aterro Sanitário,356.3,341.2,77.6,18.0,184.2,10.1,3.6,Apropriado,Residencial
288,Zona Oeste,Orgânico,Comercial,Reciclagem,674.9,316.9,78.5,5.1,94.1,8.1,8.8,Apropriado,Outros
289,Zona Oeste,Orgânico,Residencial,Compostagem,223.1,321.1,81.6,8.6,140.2,0.0,8.1,Apropriado,Residencial

In [15]:
var1= "Origem_Residuo"
var2= "Apropriado_Para_Biodigestor?"

In [16]:
df.head()

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg,Apropriado_Para_Biodigestor?,Origem_Residuo_Classificado
0,Centro,Reciclável,Residencial,Reciclagem,345.0,112.3,2.0,15.3,167.7,83.3,21.2,Inapropriado,Residencial
1,Centro,Reciclável,Industrial,Aterro Sanitário,1007.2,50.7,2.0,6.1,124.7,79.4,20.1,Inapropriado,Outros
2,Zona Leste,Reciclável,Industrial,Incineração,1551.8,57.0,2.0,4.3,118.9,87.6,19.8,Inapropriado,Outros
3,Zona Norte,Reciclável,Serviços de Saúde,Aterro Sanitário,89.6,57.3,2.0,3.5,124.1,94.6,19.8,Inapropriado,Outros
4,Zona Leste,Reciclável,Serviços de Saúde,Reciclagem,48.7,162.2,2.0,12.2,129.8,91.8,19.5,Inapropriado,Outros

In [17]:
df_tabela_cruz=pd.crosstab(df[var1],df[var2],margins=True)

#Podemos renomear a coluna All para o Português:
df_tabela_cruz.rename(columns={'All': 'Total'}, inplace = True)
#Podemos renomear a linha All para o Português:
df_tabela_cruz.rename(index={'All': 'Total'}, inplace = True)

In [18]:
df_tabela_cruz

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                             22            45     67
Industrial                            19            39     58
Residencial                           39           104    143
Serviços de Saúde                      6            16     22
Total                                 86           204    290

In [19]:
df_tabela_cruz_porcentagem = (pd.crosstab(df[var1], df[var2], margins = True, normalize= True)*100).round(1)
df_tabela_cruz_porcentagem.rename(index={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem.rename(columns={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                            7.6          15.5   23.1
Industrial                           6.6          13.4   20.0
Residencial                         13.4          35.9   49.3
Serviços de Saúde                    2.1           5.5    7.6
Total                               29.7          70.3  100.0

In [20]:
df_tabela_cruz_porcentagem_linhas = (pd.crosstab(df[var1], df[var2], margins = True, normalize='index')*100).round(1)
df_tabela_cruz_porcentagem_linhas.rename(index={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem_linhas

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado
Origem_Residuo
Comercial                           32.8          67.2
Industrial                          32.8          67.2
Residencial                         27.3          72.7
Serviços de Saúde                   27.3          72.7
Total                               29.7          70.3

In [21]:
df_tabela_cruz_porcentagem_colunas = (pd.crosstab(df[var1], df[var2], margins = True, normalize='columns')*100).round(1)
df_tabela_cruz_porcentagem_colunas.rename(columns={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem_colunas

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                           25.6          22.1   23.1
Industrial                          22.1          19.1   20.0
Residencial                         45.3          51.0   49.3
Serviços de Saúde                    7.0           7.8    7.6

In [22]:
df_tabela_cruz

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                             22            45     67
Industrial                            19            39     58
Residencial                           39           104    143
Serviços de Saúde                      6            16     22
Total                                 86           204    290

In [23]:
df_tabela_cruz_porcentagem

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                            7.6          15.5   23.1
Industrial                           6.6          13.4   20.0
Residencial                         13.4          35.9   49.3
Serviços de Saúde                    2.1           5.5    7.6
Total                               29.7          70.3  100.0

In [24]:
df_tabela_cruz_porcentagem_linhas

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado
Origem_Residuo
Comercial                           32.8          67.2
Industrial                          32.8          67.2
Residencial                         27.3          72.7
Serviços de Saúde                   27.3          72.7
Total                               29.7          70.3

In [25]:
df_tabela_cruz_porcentagem_colunas

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                           25.6          22.1   23.1
Industrial                          22.1          19.1   20.0
Residencial                         45.3          51.0   49.3
Serviços de Saúde                    7.0           7.8    7.6

In [28]:
var3 = "Origem_Residuo_Classificado"
var4 = "Apropriado_Para_Biodigestor?"

In [30]:
df_tabela_cruz2=pd.crosstab(df[var3],df[var4],margins=True)

#Podemos renomear a coluna All para o Português:
df_tabela_cruz2.rename(columns={'All': 'Total'}, inplace = True)
#Podemos renomear a linha All para o Português:
df_tabela_cruz2.rename(index={'All': 'Total'}, inplace = True)

df_tabela_cruz2

Apropriado_Para_Biodigestor?  Apropriado  Inapropriado  Total
Origem_Residuo_Classificado
Outros                                47           100    147
Residencial                           39           104    143
Total                                 86           204    290

In [35]:
# Cálculo do risco relativo da apropriação do lixo residencial com relação ao lixo advindos de outros meios

a = df_tabela_cruz2.loc['Residencial','Apropriado']
b = df_tabela_cruz2.loc['Outros','Apropriado']
tot1 = df_tabela_cruz2.loc['Residencial','Total']
tot2 = df_tabela_cruz2.loc['Outros','Total']

rr = (a/tot1)/(b/tot2)
rr

np.float64(0.852998065764023)

In [27]:
writer=pd.ExcelWriter('Tabelas_Cruzadas.xlsx')
df_tabela_cruz.to_excel(writer, sheet_name="Tab_cruz_abs",index=True)
df_tabela_cruz_porcentagem.to_excel(writer, sheet_name="Tab_Cruzada_porc", index=True)
df_tabela_cruz_porcentagem_linhas.to_excel(writer, sheet_name="Tab_Cruzada_porc_linhas",index=True)
df_tabela_cruz_porcentagem_colunas.to_excel(writer, sheet_name="Tab_Cruzada_porc_colunas", index=True)
writer.close()