In [1]:
import pandas as pd

In [2]:
arquivo='Solid_waste_pt_categorizado.xlsx'

In [4]:
df=pd.read_excel(arquivo)

In [15]:
df

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg,Apropriado_Para_Incineracao?
0,Zona Oeste,Orgânico,Residencial,Compostagem,223.1,321.1,81.6,8.6,140.2,0.0,8.1,Inapropriado
1,Zona Oeste,Orgânico,Comercial,Reciclagem,674.9,316.9,78.5,5.1,94.1,8.1,8.8,Inapropriado
2,Zona Leste,Orgânico,Residencial,Aterro Sanitário,356.3,341.2,77.6,18.0,184.2,10.1,3.6,Inapropriado
3,Zona Norte,Orgânico,Comercial,Aterro Sanitário,471.8,338.4,77.2,52.9,262.3,5.0,8.1,Inapropriado
4,Zona Leste,Orgânico,Residencial,Aterro Sanitário,275.9,371.8,77.0,17.2,178.8,5.2,6.5,Inapropriado
...,...,...,...,...,...,...,...,...,...,...,...,...
285,Zona Sul,Reciclável,Comercial,Aterro Sanitário,1057.3,80.8,2.0,14.7,138.7,79.7,15.1,Apropriado
286,Zona Norte,Reciclável,Residencial,Aterro Sanitário,417.7,116.6,2.0,16.8,142.8,79.1,14.8,Apropriado
287,Zona Leste,Reciclável,Comercial,Aterro Sanitário,527.1,40.0,2.0,16.7,164.2,88.0,14.7,Apropriado
288,Centro,Reciclável,Comercial,Reciclagem,529.7,72.7,2.0,24.0,223.2,81.6,13.9,Apropriado
289,Zona Oeste,Reciclável,Residencial,Aterro Sanitário,389.3,40.0,2.0,27.2,192.3,91.6,13.9,Apropriado

In [34]:
var1= "Origem_Residuo"
var2= "Apropriado_Para_Incineracao?"

In [35]:
df.head()

,Regiao_Coleta,Tipo_Residuo,Origem_Residuo,Metodo_Destinacao,Massa_Coletada_kg,Densidade_Residuo_kgm3,Umidade_Residuo_pct,Distancia_Destinacao_km,Custo_Coleta_Transporte_RS_ton,Indice_Reciclabilidade_pct,Poder_Calorifico_MJkg,Apropriado_Para_Incineracao?
0,Zona Oeste,Orgânico,Residencial,Compostagem,223.1,321.1,81.6,8.6,140.2,0.0,8.1,Inapropriado
1,Zona Oeste,Orgânico,Comercial,Reciclagem,674.9,316.9,78.5,5.1,94.1,8.1,8.8,Inapropriado
2,Zona Leste,Orgânico,Residencial,Aterro Sanitário,356.3,341.2,77.6,18.0,184.2,10.1,3.6,Inapropriado
3,Zona Norte,Orgânico,Comercial,Aterro Sanitário,471.8,338.4,77.2,52.9,262.3,5.0,8.1,Inapropriado
4,Zona Leste,Orgânico,Residencial,Aterro Sanitário,275.9,371.8,77.0,17.2,178.8,5.2,6.5,Inapropriado

In [36]:
df_tabela_cruz=pd.crosstab(df[var1],df[var2],margins=True)

#Podemos renomear a coluna All para o Português:
df_tabela_cruz.rename(columns={'All': 'Total'}, inplace = True)
#Podemos renomear a linha All para o Português:
df_tabela_cruz.rename(index={'All': 'Total'}, inplace = True)

In [37]:
df_tabela_cruz

Apropriado_Para_Incineracao?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                             31            36     67
Industrial                            26            32     58
Residencial                           68            75    143
Serviços de Saúde                     12            10     22
Total                                137           153    290

In [38]:
df_tabela_cruz_porcentagem = (pd.crosstab(df[var1], df[var2], margins = True, normalize= True)*100).round(1)
df_tabela_cruz_porcentagem.rename(index={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem.rename(columns={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem

Apropriado_Para_Incineracao?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                           10.7          12.4   23.1
Industrial                           9.0          11.0   20.0
Residencial                         23.4          25.9   49.3
Serviços de Saúde                    4.1           3.4    7.6
Total                               47.2          52.8  100.0

In [39]:
df_tabela_cruz_porcentagem_linhas = (pd.crosstab(df[var1], df[var2], margins = True, normalize='index')*100).round(1)
df_tabela_cruz_porcentagem_linhas.rename(index={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem_linhas

Apropriado_Para_Incineracao?  Apropriado  Inapropriado
Origem_Residuo
Comercial                           46.3          53.7
Industrial                          44.8          55.2
Residencial                         47.6          52.4
Serviços de Saúde                   54.5          45.5
Total                               47.2          52.8

In [40]:
df_tabela_cruz_porcentagem_colunas = (pd.crosstab(df[var1], df[var2], margins = True, normalize='columns')*100).round(1)
df_tabela_cruz_porcentagem_colunas.rename(columns={'All': 'Total'}, inplace = True)
df_tabela_cruz_porcentagem_colunas

Apropriado_Para_Incineracao?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                           22.6          23.5   23.1
Industrial                          19.0          20.9   20.0
Residencial                         49.6          49.0   49.3
Serviços de Saúde                    8.8           6.5    7.6

In [41]:
df_tabela_cruz

Apropriado_Para_Incineracao?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                             31            36     67
Industrial                            26            32     58
Residencial                           68            75    143
Serviços de Saúde                     12            10     22
Total                                137           153    290

In [42]:
df_tabela_cruz_porcentagem

Apropriado_Para_Incineracao?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                           10.7          12.4   23.1
Industrial                           9.0          11.0   20.0
Residencial                         23.4          25.9   49.3
Serviços de Saúde                    4.1           3.4    7.6
Total                               47.2          52.8  100.0

In [43]:
df_tabela_cruz_porcentagem_linhas

Apropriado_Para_Incineracao?  Apropriado  Inapropriado
Origem_Residuo
Comercial                           46.3          53.7
Industrial                          44.8          55.2
Residencial                         47.6          52.4
Serviços de Saúde                   54.5          45.5
Total                               47.2          52.8

In [45]:
df_tabela_cruz_porcentagem_colunas

Apropriado_Para_Incineracao?  Apropriado  Inapropriado  Total
Origem_Residuo
Comercial                           22.6          23.5   23.1
Industrial                          19.0          20.9   20.0
Residencial                         49.6          49.0   49.3
Serviços de Saúde                    8.8           6.5    7.6

In [33]:
writer=pd.ExcelWriter('Tabelas_Cruzadas.xlsx')
df_tabela_cruz.to_excel(writer, sheet_name="Tab_cruz_abs",index=True)
df_tabela_cruz_porcentagem.to_excel(writer, sheet_name="Tab_Cruzada_porc", index=True)
df_tabela_cruz_porcentagem_linhas.to_excel(writer, sheet_name="Tab_Cruzada_porc_linhas",index=True)
df_tabela_cruz_porcentagem_colunas.to_excel(writer, sheet_name="Tab_Cruzada_porc_colunas", index=True)
writer.close()